package clases;
// Generated 31 ene 2023 18:12:08 by Hibernate Tools 5.4.33.Final

/**
 * Miembro generated by hbm2java
 */
public class Miembro implements java.io.Serializable {

	private Integer codMiembro;
	private Ministerio ministerio;
	private String nif;
	private String nombre;
	private String apellido1;
	private String alias;

	public Miembro() {
	}

	public Miembro(String nif, String nombre, String apellido1) {
		this.nif = nif;
		this.nombre = nombre;
		this.apellido1 = apellido1;
	}

	public Miembro(Ministerio ministerio, String nif, String nombre, String apellido1, String alias) {
		this.ministerio = ministerio;
		this.nif = nif;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.alias = alias;
	}

	public Integer getCodMiembro() {
		return this.codMiembro;
	}

	public void setCodMiembro(Integer codMiembro) {
		this.codMiembro = codMiembro;
	}

	public Ministerio getMinisterio() {
		return this.ministerio;
	}

	public void setMinisterio(Ministerio ministerio) {
		this.ministerio = ministerio;
	}

	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	public String getAlias() {
		return this.alias;
	}

	public void setAlias(String alias) {
		this.alias = alias;
	}

}
