package clases;
// Generated 31 ene 2023 18:12:08 by Hibernate Tools 5.4.33.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ministerio generated by hbm2java
 */
public class Ministerio implements java.io.Serializable {

	@Override
	public String toString() {
		return "Ministerio [codMinisterio=" + codMinisterio + ", nombre=" + nombre + ", presupuesto=" + presupuesto
				+ ", gastos=" + gastos +  "]";
	}

	private Integer codMinisterio;
	private String nombre;
	private double presupuesto;
	private double gastos;
	private Set miembros = new HashSet(0);

	public Ministerio() {
	}

	public Ministerio(String nombre, double presupuesto, double gastos) {
		this.nombre = nombre;
		this.presupuesto = presupuesto;
		this.gastos = gastos;
	}

	public Ministerio(String nombre, double presupuesto, double gastos, Set miembros) {
		this.nombre = nombre;
		this.presupuesto = presupuesto;
		this.gastos = gastos;
		this.miembros = miembros;
	}

	public Integer getCodMinisterio() {
		return this.codMinisterio;
	}

	public void setCodMinisterio(Integer codMinisterio) {
		this.codMinisterio = codMinisterio;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public double getPresupuesto() {
		return this.presupuesto;
	}

	public void setPresupuesto(double presupuesto) {
		this.presupuesto = presupuesto;
	}

	public double getGastos() {
		return this.gastos;
	}

	public void setGastos(double gastos) {
		this.gastos = gastos;
	}

	public Set getMiembros() {
		return this.miembros;
	}

	public void setMiembros(Set miembros) {
		this.miembros = miembros;
	}

}
